### ISSUE TITLE
Wrong & Unused keys

### ISSUE THREAD

**Issue by DustInCompetent** [Frooxius/NeosLocale#125]
While checking translations, I noticed that some strings configurable in the locales are not used in the UI:

* The registration dialog uses the key `Account.Email` twice, instead of using `Account.RepeatEmail` for the second field.
![image](https://user-images.githubusercontent.com/5402623/98448551-0d944d80-212d-11eb-80f8-d042b4306af8.png)

* `World.AccessLevel.*` match the options on the Session Settings screen but don't seem to be used.
![image](https://user-images.githubusercontent.com/5402623/98448617-957a5780-212d-11eb-8c7b-8bf3b4e85b3d.png)

**Comment by Frooxius** [comment]
Fixed in 2020.11.13.1356, thanks!
