### ISSUE TITLE
MTC 2.0 tutorial welcome page is not being localized even though the translated strings are present

### ISSUE THREAD

**Issue by rampa3** [Frooxius/NeosLocale#148]
The welcome page of the tutorial UI in MTC 2.0 is not being localised, while other pages are localized without a problem.
![obrazek](https://user-images.githubusercontent.com/68955305/99287676-7a48cf80-2832-11eb-857f-deb5703f1466.png)
![obrazek](https://user-images.githubusercontent.com/68955305/99287747-8cc30900-2832-11eb-815f-89e3c9ad4ae0.png)

**Comment by Frooxius** [comment]
Should be fixed now, thanks!
