### ISSUE TITLE
Typos found in the string IDs

### ISSUE THREAD

**Issue by rampa3** [Frooxius/NeosLocale#169]
@Frooxius  I have found typos in the string IDs, for the light sources wizard. I have them fixed in CS and EN copies that will come in my next PR. A check of Neos might be needed to make sure that these are not in the source code too.

![obrazek](https://user-images.githubusercontent.com/68955305/99957259-4d8b3f80-2d7f-11eb-9251-3f7b7ecd9f6b.png)

**Comment by rampa3** [comment]
Waiting for instructions... I might have to do some fixes to not break the merge.

**Comment by Frooxius** [comment]
Thanks! I've added a mechanism which applies to fix to all locales in one go, so they don't have to be fixed individually. If you find any more typos let me know and I'll apply them globally.
