### ISSUE TITLE
Key Settings.HideContactNameplates is missing in source language file (en.json)

### ISSUE THREAD

**Issue by rampa3** [Frooxius/NeosLocale#173]
The string key for the nameplate hiding in settings (Settings.HideContactNameplates) is not included in the source language file (en.json). It is only in the missing keys list (MISSING.md).

**Comment by Frooxius** [comment]
This key was removed before release, it seems the files didn't get updated for some reason in the MISSING.md,  You can safely ignore it. Sorry for the confusion!
