### ISSUE TITLE
Oddly-worded Autosave Interval String

### ISSUE THREAD

**Issue by yellowcrash10** [Frooxius/NeosLocale#185]
While translating, I noticed the string for [World.Config.AutosaveInterval](https://github.com/Frooxius/NeosLocale/blob/ba94e269746f669065d1069b197ed921ad134ca1/en.json#L137) is oddly worded. It says "Autosave every minutes:", but it would be more logical if it said "Autosave interval (minutes):". It would then follow the format of a similar option on that screen, "Cleanup interval (seconds)".

**Comment by Frooxius** [comment]
Fixed this in 2020.12.2.583, thanks!
